# Generated by Django 3.1 on 2020-08-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.PositiveIntegerField()),
                ('pol_year', models.PositiveSmallIntegerField()),
                ('end_sequence', models.PositiveSmallIntegerField()),
                ('sub_code', models.PositiveSmallIntegerField()),
                ('agent_master_code', models.PositiveIntegerField()),
                ('agent_no', models.PositiveIntegerField()),
                ('line_of_business', models.PositiveIntegerField()),
                ('transaction_type', models.PositiveSmallIntegerField()),
                ('search_name', models.CharField(max_length=50)),
                ('eff_date', models.DateField()),
                ('location_city', models.CharField(max_length=50)),
                ('location_state', models.CharField(max_length=2)),
                ('state_name', models.CharField(max_length=50)),
                ('action_type', models.CharField(max_length=35)),
                ('trans_code', models.PositiveSmallIntegerField()),
                ('document_name', models.CharField(max_length=50)),
                ('run_date', models.DateField(auto_now_add=True)),
                ('policy_exp_date', models.DateField()),
                ('copy_name', models.CharField(max_length=25)),
            ],
        ),
    ]
