# Generated by Django 3.1 on 2020-08-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentmanagement',
            old_name='policy',
            new_name='policy_no',
        ),
    ]
