# Generated by Django 3.1 on 2020-08-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20200812_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentmanagement',
            options={'verbose_name': 'DocumentManagement', 'verbose_name_plural': 'DocumentManagements'},
        ),
        migrations.AlterField(
            model_name='documentmanagement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='documentmanagement',
            table='DocumentManagement',
        ),
    ]
