# Generated by Django 3.1 on 2020-08-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20200812_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmanagement',
            name='transaction_type',
            field=models.CharField(max_length=50),
        ),
    ]
